apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: stevenwetten/bargainbot:worker
          ports:
            - name: worker-port
              containerPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: app
          image: stevenwetten/bargainbot:mysql
          resources:
            requests:
              cpu: 10m
          ports:
            - name: mysql-port
              containerPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: stevenwetten/bargainbot:webui
          ports:
            - name: http-port
              containerPort: 80
