apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 32010
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: webui
