apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: 11jamesp/cloud468:webui
        ports:
        - containerPort: 80
