apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: yourusername/web-ui:latest  # Use the correct image path
        ports:
        - containerPort: 80
