CREATE TABLE csc468.cattle (BROWN INT, BLACK INT, WHITE INT);
LOAD DATA INFILE '/cattle.csv'
INTO TABLE csc468.cattle
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
